import {
  USERNAME_REQUIRED_ERROR,
  EMAIL_REQUIRED_ERROR,
  PASSWORDS_MISMATCH_ERROR,
} from '../../../shared/config';

const PASSWORD_CONFIRMATION_REQUIRED_ERROR = 'Please, confirm new password';

export {
  USERNAME_REQUIRED_ERROR,
  EMAIL_REQUIRED_ERROR,
  PASSWORDS_MISMATCH_ERROR,
  PASSWORD_CONFIRMATION_REQUIRED_ERROR,
};
